# Generated by Django 4.2.13 on 2024-11-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_stock_delete_measurement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
