# Generated by Django 4.2.13 on 2024-11-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signal',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
